export const SET_YOU_TUBE_SEARCH_RESULTS = 'SET_YOU_TUBE_SEARCH_RESULTS';
export const UPDATE_YOU_TUBE_SEARCH_RESULTS = 'UPDATE_YOU_TUBE_SEARCH_RESULTS';
export const RESET_YOU_TUBE_SEARCH_RESULTS = 'RESET_YOU_TUBE_SEARCH_RESULTS';

export const SET_YOU_TUBE_SEARCH_KEYWORD = 'SET_YOU_TUBE_SEARCH_KEYWORD';
export const RESET_YOU_TUBE_SEARCH_KEYWORD = 'RESET_YOU_TUBE_SEARCH_KEYWORD';

export const ADD_API_FAILURE_STATUS = 'ADD_API_FAILURE_STATUS';
export const REMOVE_API_FAILURE_STATUS = 'REMOVE_API_FAILURE_STATUS';
